### ISSUE TITLE
Support gulp vinyl streams

### ISSUE THREAD

**Issue by scottohara** [GoogleChrome/sw-precache#54] opened 2015-11-19 05:12 UTC
Not sure if this is possible currently...but I was thinking that it might be useful if the module supported vinyl streams.

This would allow further processing on the generated service worker script (eg. minify, create source maps etc.) before writing it out, using standard stream functions, e.g. `.pipe()`, `.dest()`.

Not that service worker scripts are large; but...minify all the things!

Something along the lines of:

```
const sourceMaps = require("gulp-sourcemaps"),
      swPrecache = require("sw-precache"),
      uglify = require("gulp-uglify"),
      util = require("gulp-util"),

      // Options for generating service worker
      swOptions = {
        scriptName: "my-service-worker.js",  // new option (default: 'service-worker.js')
        cacheId: "my-app",
        staticFileGlobs: ["dist/**/*.{html,js,css}"],
        stripPrefix: "dist",
        logger: util.log
      };

// Generate minified service worker & source map
gulp.task("build:serviceworker", () => swPrecache.generate(swOptions)
  .pipe(sourceMaps.init())
    .pipe(uglify())
  .pipe(sourceMaps.write("."))
  .pipe(gulp.dest("dist"))
  .on("error", util.log));
```

The above would create a minified `/dist/my-service-worker.js`, along with a corresponding `/dist/my-service-worker.js.map` source map.

**Comment by jeffposnick** [comment] 2015-11-19 20:01
Thanks for the suggestion! I've thought about minification before, but have avoided promoting that approach for the generated service worker JS file due to the way the service worker update flow works.

If there's even a one-byte change in the service worker JS file, the update flow (`install` → `activate`) is kicked off. `sw-precache` takes advantage of the update flow to incrementally update and purge the cache when there's a change to any of the files/hashes listed in the service worker JS file.

I'm uncertain whether/which minifiers produce repeatable output given the same input, so you may end up generating service worker JS files that would otherwise be identical, but end up triggering the update flow due to a minifier deciding to reorder a object property or the like.

Those extra update flows probably wouldn't cause unintended behavior, but at the same time, I like having the certainty that if the update flow is triggered, it's because something actually changed in the config or list of files that are cached.

So I'm going to close this for now, but if you know of any minifiers that guarantee repeatable output, I'd reconsider opening it and adding in whatever would be needed on the Vinyl streams front.

**Closed by jeffposnick** 2015-11-19 20:01 UTC
