### ISSUE TITLE
Service Worker in html5-routed web app

### ISSUE THREAD

**Issue by jcdesousa** [GoogleChrome/sw-precache#253] opened 2017-02-24 14:29 UTC
Hi everyone, i have a issue when navigating offline to https://example.com/an-html5-route it does not load the index.html.

I added the navigateFallback: '/index.html', but the page does not load and i don't have any service worker installed when i go to Application -> Service Workers.

`$locationProvider.html5Mode(true).hashPrefix('!');`

Everything works fine with https://example.com, even when offline.

Thanks.

**Comment by jeffposnick** [comment] 2017-02-27 15:50
Figuring out why there's no installed service worker is the most important thing, since if you don't have a service worker installed, there's no chance that there will be offline support.

Do you see anything logged in the JavaScript console when you navigate to a page that tries to install the service worker? Can you pass along a URL at which we can reproduce the issue?

**Comment by barinali** [comment] 2017-03-21 09:10
You should provide some more information. Because I think example.com isn't where you're actually working on. So we can't inspect/debug it. Nowadays, I've been working with Service Worker API. I brought offline support to our React web application by using `sw-precache`. Could you share your service worker code?

**Comment by jeffposnick** [comment] 2017-06-12 17:26
Closing due to lack of follow-up from the original poster. Please reopen with the detail provided if this is still an issue.

**Closed by jeffposnick** 2017-06-12 17:26 UTC
